---
  - name: Update ubuntu
    apt:
      update_cache: yes
  
  - name: install base
    apt:
      name: "{{ base_packges_ubuntu }}"
      state: latest
  
  - name: update timezone
    timezone:
      name: Asia/Tokyo
  
  - name: Set max openfile for all user
    pam_limits:
      domain: "*"
      limit_type: "-"
      limit_item: nofile
      value: 65535
       
  - name: RUBY --> Create Group Developer
    group:
      name: dev
      uid: "401"
      state: present

### Ubuntu ###
  - name: RUBY --> Create Group Admin
    group:
      name: admin
      uid: "400"
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: RUBY --> Create user deploy in UBUNTU
    user:
      name: "{{ user_deploy }}"
      shell: /bin/bash
      groups: admin,dev
      append: yes
    when: ansible_distribution == "Ubuntu"

  - name: RUBY --> Add permission for Group ADMIN
    lineinfile:
      path: /etc/suoders
      state: present
      regexp: "^%admin"
      line: "%admin ALL=(ALL:ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"

### CentOS ###  
  - name: RUBY --> Create user deploy in CENTOS
    user:
      name: "{{ user_deploy }}"
      shell: /bin/bash
      groups: wheel,dev
      append: yes
    when: ansible_distribution == "Centos"

  - name: RUBY --> Add permission for Group WHEEL
    lineinfile:
      path: /etc/suoders
      state: present
      regexp: "^%wheel"
      line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"

  - name: Create a 2048-bit SSH key for user 
    user:
      name: "{{ user_deploy }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa