--- #play example
- hosts: study
  become: yes
  tasks:
    - name: install software
      apt: 
        name: elinks
        state: latest
    - name: install more software
      apt:
        name: nmap
        state: latest