### Fix CIS 3.2.4  Ensure suspicious packets are logged ###
- name: Insert fix 3.2.4
  become: yes
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.conf.default.log_martians = 1

### Fix CIS 5.2.1 ###
- name: Ensure permission ssh_config
  become: yes
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"

### Fix CIS 5.2.4 disable X11Forwarding ###
- name: Disable X11Forwarding
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding yes'
    line: 'X11Forwarding no'

### Fix CIS 5.2.8  Ensure SSH root login is disabled ###
- name: Ensure SSH root login is disabled
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin prohibit-password'
    line: 'PermitRootLogin no'

### Fix CIS  5.2.5,5.2.11, 5.2.12, 5.2.13 ###
- name: 5.2.5,5.2.11, 5.2.12, 5.2.13 
  become: yes
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      MaxAuthTries 4
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
      ClientAliveInterval 600
      ClientAliveCountMax 0
      LoginGraceTime 60