  
---
    - name: Ensure Redis is installed.
      apt:
        name: "{{ redis_package }}"
        state: present
    
    - name: Ensure Redis is running and enabled on boot.
      service: 
        name: "{{ redis_daemon }}"
        state: started 
        enabled: yes