---
- hosts: nfs
  become: yes
  vars:
    share_path: /mnt/nfsroot
  tasks:
    - name: Install nfs-utils
      yum: 
        name: nfs-utils
        state: latest
    - name: Start server NFS
      service:
        state: started
        name: nfs-server
#        enable: yes
    - name: config export NFS
      template:
        src: /home/ansible/exports.j2
        dest: /etc/exports
      notify: update nfs
  handlers:
    - name: update nfs exports
      command: exportfs -a
      listen: update nfs
- hosts: remote
  become: yes
  vars:
    nfs_ip: "{{ hostvars['nfs']['ansible_default_ipv4']['address'] }}"
    nfs_hostname: "{{ hostvars['nfs']['ansible_hostname'] }}"
  vars_files:
    - /home/ansible/user-list.txt
  tasks: 
    - name: Config hosts file
      template:
        src: /home/ansible/etc.hosts.j2
        dest: /etc/hosts.nfslab
#      notify: update hosts
    - name: Check file user-agreement.txt
      stat:
        path: /opt/user-agreement.txt
      register: filestat
    - name: check info
      debug:
        var: filestat
    - name: create user
      user:
        name: "{{ item }}"
      when: filestat.stat.exists
      loop: "{{ users }}"
