--- 
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/confidential
  tasks:
    - name: Install httpd
      yum:
       name: httpd
       state: latest
      notify: httpd service
      tags:
        - httpd-base-install
    - name: update vhost.conf
      template:
        src: /home/ansible/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: httpd service
      tags:
        - vhost
    - name: update htpasswd
      template:
        src: /home/ansible/htpasswd.j2
        dest: /etc/httpd/conf/htpasswd
      notify: httpd service
      tags:
        - vhost
    - name: Run data job
      command: /opt/data-job.sh
      async: 600
      poll: 0
      tags:
        - data-job
  handlers:
    - name: Enable httpd
      service:
        name: httpd
        state: restarted
        enable: yes
      listen: httpd service