- name:  Create Application folder
  file:
    path: /usr/local/rails_app
    state: directory
    owner: '{{ user_deploy }}'
    group: '{{ user_deploy }}'

- name: Create deploy_bin
  file:
    path: /home/{{ user_deploy }}/deploy_bin
    state: directory
    owner: '{{ user_deploy }}'
    group: '{{ user_deploy }}'

- name: Upload file script
  template:
    src: ../script/{{ item }}
    dest: /home/{{ user_deploy }}/deploy_bin
  with_items:
    -  
