  
---
    - name: REDIS ----> Create Group Redis
      group:
        name: redis
        state: present

    - name: REDIS ----> Create User redis
      user:
        name: redis
        uid: 900
        group: redis
      
    - name: REDIS ----> Get specific version
      get_url:
        url: http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
        dest: /tmp
    
    - name: REDIS ----> Extract redis-server
      unarchive:
        src: /tmp/redis-{{ redis_version }}.tar.gz
        dest: /tmp
        remote_src: yes

    - name: REDIS ----> Build Redis-server
      make: 
        chdir: /tmp/redis-{{ redis_version }}

    - name: REDIS ----> Install Redis-server
      make:
        chdir: /tmp/redis-{{ redis_version }}     
        target: install

    - name: REDIS ----> Create foder Redis configure
      file:
        path: /etc/redis
        state: directory
        mode: '0755'

    - name: REDIS ----> Setup Redis configure file
      copy:
        src: /tmp/redis-{{ redis_version }}/redis.conf
        dest: /etc/redis/redis.conf
        remote_src: yes

    - name: REDIS ----> Set REDIS connect form everywhere ( IF NEED )
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'bind 127.0.0.1'
        line: 'bind 0.0.0.0'
    
    - name: REDIS ----> Set directory install DB
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^dir ./'
        line: 'dir /var/lib/redis'
    
    - name: REDIS ----> Create DB directory
      file:
        path: /var/lib/redis
        state: directory
        owner: redis
        group: redis
        mode: '765'
    
    - name: REDIS ----> Create Redis.service
      template:
        src: redis.service.j2
        dest: /etc/systemd/system/redis.service
        mode: '765'

    
    - name: REDIS -----> Ensure Redis is running and enabled on boot.
      service: 
        name: "redis"
        state: started 
        enabled: yes